import { useCallback, useEffect, useState, type FormEvent } from "react";
import { NavLink, Route, Routes, useNavigate } from "react-router-dom";
import { AlertTriangle, ArrowRight, BookOpen, Check, ChevronRight, CircleUserRound, Clock3, FileDiff, FileLock2, Home, LifeBuoy, LockKeyhole, MessageSquareText, Plus, Settings, ShieldCheck, Sparkles, Users, WifiOff, X } from "lucide-react";
import { db, type Household, type PrivateRecord } from "../data/db";
import type { AuditEntry, CapabilityLease, Consent, ContractVersion, CooldownSession, MemberNode, Revision } from "../domain/types";
import { decryptJson, deriveKey, encryptJson, randomSalt, type EncryptedPayload } from "../data/crypto";
import { PrivateRepository } from "../data/repositories/privateRepository";
import { convertWithLocalTemplate } from "../ai/local-template";
import { inspectLease, inspectPatch, PROTOCOL_CONSTITUTION } from "../domain/constitution";
import { evaluateConsensus } from "../domain/consensus";
import { mergeRevision } from "../domain/revision";
import { createCooldown, closeCooldown, cooldownState } from "../domain/cooldown";
import { issueLease, leaseState } from "../domain/safety";
import { appendAudit, verifyAuditChain } from "../domain/audit";
import { deleteAllData, exportEncrypted, importEncrypted } from "../data/export";

type MonkuValue = { body: string };
type SafeContact = { name: string; contact: string };
type SafetyValue = { note: string; action: "local" | "contact" | "emergency" };
type Snapshot = { household?: Household; members: MemberNode[]; contracts: ContractVersion[]; revisions: Revision[]; consents: Consent[]; cooldowns: CooldownSession[]; leases: CapabilityLease[]; audit: AuditEntry[] };

const emptySnapshot: Snapshot = { members: [], contracts: [], revisions: [], consents: [], cooldowns: [], leases: [], audit: [] };
const privateRepo = new PrivateRepository();
const nowIso = () => new Date().toISOString();
const uid = () => crypto.randomUUID();

async function writeAudit(actorId: string, action: string, resourceType: string, resourceId: string) {
  const entries = await db.audit.orderBy("timestamp").toArray();
  await db.audit.add(await appendAudit(entries, { actorId, action, resourceType, resourceId }));
}

export default function App() {
  const [data, setData] = useState<Snapshot>(emptySnapshot);
  const [member, setMember] = useState<MemberNode>();
  const [sessionKey, setSessionKey] = useState<CryptoKey>();
  const [loading, setLoading] = useState(true);
  const [online, setOnline] = useState(navigator.onLine);
  const navigate = useNavigate();

  const refresh = useCallback(async () => {
    const [household, members, contracts, revisions, consents, cooldowns, leases, audit] = await Promise.all([
      db.households.toCollection().first(), db.members.toArray(), db.contracts.orderBy("createdAt").reverse().toArray(), db.revisions.toArray(), db.consents.toArray(), db.cooldowns.toArray(), db.leases.toArray(), db.audit.orderBy("timestamp").toArray()
    ]);
    setData({ household, members, contracts, revisions, consents, cooldowns, leases, audit }); setLoading(false);
  }, []);

  useEffect(() => { refresh(); const update = () => setOnline(navigator.onLine); addEventListener("online", update); addEventListener("offline", update); return () => { removeEventListener("online", update); removeEventListener("offline", update); }; }, [refresh]);
  const unlock = useCallback(async (selected: MemberNode, pin: string) => { const salt = String((await db.settings.get(`salt:${selected.id}`))?.value ?? ""); const verifier = (await db.settings.get(`verifier:${selected.id}`))?.value as EncryptedPayload | undefined; if (!salt || !verifier) return false; try { const key = await deriveKey(pin, salt); const marker = await decryptJson<string>(verifier, key); if (marker !== `aperture:${selected.id}`) return false; setSessionKey(key); setMember(selected); navigate("/"); return true; } catch { return false; } }, [navigate]);
  const enroll = useCallback(async (selected: MemberNode, pin: string) => { if (pin.length < 6 || await db.settings.get(`verifier:${selected.id}`)) return false; const salt = randomSalt(); const key = await deriveKey(pin, salt); await db.settings.bulkPut([{ key: `salt:${selected.id}`, value: salt }, { key: `verifier:${selected.id}`, value: await encryptJson(`aperture:${selected.id}`, key) }]); await writeAudit(selected.id, "local-account-enrolled", "member", selected.id); setSessionKey(key); setMember(selected); navigate("/"); return true; }, [navigate]);
  const lock = () => { setSessionKey(undefined); setMember(undefined); navigate("/"); };

  if (loading) return <div className="center-screen"><div className="aperture-loader"/><p>端末内の記録を開いています</p></div>;
  if (!data.household) return <Onboarding onDone={async (selected, key) => { setMember(selected); setSessionKey(key); await refresh(); }} />;
  if (!member || !sessionKey) return <Unlock household={data.household} members={data.members} onUnlock={unlock} onEnroll={enroll} />;

  const context = { data, member, sessionKey, refresh };
  return <div className="app-frame">
    <header className="topbar">
      <NavLink to="/" className="brand" aria-label="Aperture Home"><span className="brand-mark"><span/></span><span>Aperture <b>Home</b></span></NavLink>
      <div className="top-actions">{!online && <span className="offline"><WifiOff size={14}/> オフライン</span>}<button className="member-chip" onClick={lock}><CircleUserRound size={17}/><span>{member.displayName}</span><LockKeyhole size={13}/></button></div>
    </header>
    <main className="main-content">
      <Routes>
        <Route path="/" element={<Today {...context}/>} />
        <Route path="/contracts" element={<Contracts {...context}/>} />
        <Route path="/monku" element={<Monku {...context}/>} />
        <Route path="/revisions" element={<Revisions {...context}/>} />
        <Route path="/cooldown" element={<Cooldown {...context}/>} />
        <Route path="/safety" element={<Safety {...context}/>} />
        <Route path="/settings" element={<SettingsPage {...context} onReset={() => { setMember(undefined); setSessionKey(undefined); }} />} />
      </Routes>
    </main>
    <nav className="bottom-nav" aria-label="メインナビゲーション">
      <NavItem to="/" icon={<Home/>} label="Today"/><NavItem to="/contracts" icon={<BookOpen/>} label="契約"/><NavItem to="/monku" icon={<MessageSquareText/>} label="Monku"/><NavItem to="/revisions" icon={<FileDiff/>} label="Revision"/><NavItem to="/settings" icon={<Settings/>} label="設定"/>
    </nav>
    <NavLink className="sos-fab" to="/safety" aria-label="SOS・安全な選択肢を開く"><LifeBuoy/> SOS</NavLink>
  </div>;
}

function NavItem({ to, icon, label }: { to: string; icon: React.ReactNode; label: string }) { return <NavLink to={to} className={({ isActive }) => isActive ? "active" : ""}>{icon}<span>{label}</span></NavLink>; }

function Onboarding({ onDone }: { onDone: (member: MemberNode, key: CryptoKey) => void }) {
  const [step, setStep] = useState(0); const [householdName, setHouseholdName] = useState("わたしたちの家"); const [names, setNames] = useState(["Node-01", "Node-02"]); const [pin, setPin] = useState(""); const [safeName, setSafeName] = useState(""); const [safeContact, setSafeContact] = useState(""); const [includeSample, setIncludeSample] = useState(true);
  const finish = async (event: FormEvent) => { event.preventDefault(); if (pin.length < 6) return; const household: Household = { id: uid(), name: householdName, constitutionVersion: "1.0", createdAt: nowIso() }; const members: MemberNode[] = names.filter(Boolean).map((displayName) => ({ id: uid(), householdId: household.id, displayName, role: "adult", active: true })); const salt = randomSalt(); const key = await deriveKey(pin, salt); await db.transaction("rw", [db.households, db.members, db.settings], async () => { await db.households.add(household); await db.members.bulkAdd(members); await db.settings.add({ key: `salt:${members[0].id}`, value: salt }); await db.settings.add({ key: `verifier:${members[0].id}`, value: await encryptJson(`aperture:${members[0].id}`, key) }); await db.settings.add({ key: "ai-enabled", value: false }); await db.settings.add({ key: "cloud-sync-enabled", value: false }); await db.settings.add({ key: "external-send-enabled", value: false }); }); if (includeSample) { const contractId = uid(); await db.contracts.add({ id: uid(), contractId, version: 1, kind: "shared-resource", title: "火曜のゴミ出し", participants: members.map((item) => item.id), input: "分別済みのゴミ袋", output: "火曜8時までに指定集積所へ出す", sla: "毎週 火曜 08:00", boundaries: ["担当者が再交渉を希望したら停止する"], stopConditions: ["体調や安全上の理由で実行できないとき"], status: "active", createdBy: members[0].id, createdAt: nowIso() }); } if (safeName || safeContact) await privateRepo.save<SafeContact>(members[0].id, "safe-channel", { name: safeName, contact: safeContact }, key); await writeAudit(members[0].id, "household-created", "household", household.id); onDone(members[0], key); };
  return <div className="onboarding"><div className="onboarding-card">
    <div className="eyebrow">LOCAL-FIRST · EXPERIMENT</div><h1>心を裁かず、<br/>境界を整える。</h1>
    {step === 0 && <><p className="lead">Aperture Homeは、家庭の依頼・約束・期限・退出条件だけを扱います。</p><div className="notice"><ShieldCheck/><div><b>このアプリがしないこと</b><p>感情・人格・善悪を評価しません。自動通報、物理制限、クラウド同期を行いません。</p></div></div><p className="safety-copy">緊急時は、このアプリより現実の安全確保を優先してください。</p><button className="primary wide" onClick={() => setStep(1)}>理解してはじめる <ArrowRight/></button></>}
    {step === 1 && <form onSubmit={(e) => { e.preventDefault(); setStep(2); }}><label>家庭名<input value={householdName} onChange={(e) => setHouseholdName(e.target.value)} required/></label><label>メンバー（2人以上）</label>{names.map((name, i) => <div className="inline-field" key={i}><input aria-label={`メンバー${i + 1}`} value={name} onChange={(e) => setNames(names.map((n, j) => j === i ? e.target.value : n))}/>{names.length > 2 && <button type="button" className="icon-button" onClick={() => setNames(names.filter((_, j) => j !== i))}><X/></button>}</div>)}<button className="text-button" type="button" onClick={() => setNames([...names, `Node-${String(names.length + 1).padStart(2, "0")}`])}><Plus/> メンバーを追加</button><button className="primary wide">次へ <ArrowRight/></button></form>}
    {step === 2 && <form onSubmit={finish}><label>この端末利用者のPIN（6文字以上）<input type="password" value={pin} minLength={6} onChange={(e) => setPin(e.target.value)} required autoComplete="new-password"/></label><p className="field-help">秘密データの暗号鍵をPINから生成します。PIN自体は保存しません。</p><div className="form-grid"><label>Safe Channelの名前（任意）<input value={safeName} onChange={(e) => setSafeName(e.target.value)} placeholder="信頼できる親族"/></label><label>連絡先（任意）<input value={safeContact} onChange={(e) => setSafeContact(e.target.value)} placeholder="電話番号など"/></label></div><label className="check"><input type="checkbox" checked={includeSample} onChange={(e) => setIncludeSample(e.target.checked)}/>「火曜のゴミ出し」サンプル契約を追加</label><button className="primary wide">端末内に作成する <Check/></button></form>}
    <div className="steps" aria-label={`ステップ${step + 1}/3`}>{[0,1,2].map((n) => <span className={n <= step ? "done" : ""} key={n}/>)}</div>
  </div></div>;
}

function Unlock({ household, members, onUnlock, onEnroll }: { household: Household; members: MemberNode[]; onUnlock: (member: MemberNode, pin: string) => Promise<boolean>; onEnroll: (member: MemberNode, pin: string) => Promise<boolean> }) {
  const [selected, setSelected] = useState(members[0]?.id); const [pin, setPin] = useState(""); const [error, setError] = useState("");
  return <div className="unlock"><div className="unlock-card"><span className="brand-mark large"><span/></span><div className="eyebrow">{household.name}</div><h1>この端末を開く</h1><form onSubmit={async (e) => { e.preventDefault(); const item = members.find((m) => m.id === selected)!; const ok = await onUnlock(item, pin); if (!ok) setError("この利用者はこの端末で未設定か、PINが違います"); }}><label>利用者<select value={selected} onChange={(e) => { setSelected(e.target.value); setError(""); }}>{members.map((m) => <option value={m.id} key={m.id}>{m.displayName}</option>)}</select></label><label>PIN<input type="password" value={pin} onChange={(e) => setPin(e.target.value)} minLength={6} required/></label>{error && <p className="error">{error}</p>}<button className="primary wide"><LockKeyhole/> 開く</button>{error && <button type="button" className="secondary wide" onClick={async () => { const item = members.find((m) => m.id === selected)!; const ok = await onEnroll(item, pin); if (!ok) setError("登録済みの利用者です。正しいPINで開いてください"); }}>未登録なら、このPINを初期登録</button>}</form><p className="field-help">データはこのブラウザ内にあります。ネットワーク接続は不要です。未登録Nodeの初回PIN設定は本人が操作してください。</p></div></div>;
}

type PageProps = { data: Snapshot; member: MemberNode; sessionKey: CryptoKey; refresh: () => Promise<void> };
function PageHead({ eyebrow, title, children }: { eyebrow: string; title: string; children?: React.ReactNode }) { return <header className="page-head"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1></div>{children}</header>; }
function Empty({ icon, title, text }: { icon: React.ReactNode; title: string; text: string }) { return <div className="empty">{icon}<b>{title}</b><p>{text}</p></div>; }
function Status({ tone = "neutral", children }: { tone?: string; children: React.ReactNode }) { return <span className={`status ${tone}`}>{children}</span>; }

function Today(props: PageProps) {
  const activeContracts = props.data.contracts.filter((c) => c.status === "active" && c.participants.includes(props.member.id)).filter((c, i, all) => all.findIndex((x) => x.contractId === c.contractId) === i);
  const activeCooldown = props.data.cooldowns.find((c) => c.initiatedBy === props.member.id && cooldownState(c) !== "closed"); const pending = props.data.revisions.filter((r) => r.affectedNodeIds.includes(props.member.id) && r.status === "voting");
  return <><PageHead eyebrow="TODAY · LOCAL ONLY" title={`おかえりなさい、${props.member.displayName}`}><Status tone="safe"><FileLock2/> 端末内のみ</Status></PageHead><section className="hero-grid"><div className="aperture-panel"><div className="aperture-visual"><div className="ring r1"/><div className="ring r2"/><div className="core"/></div><div><span className="micro">CONNECTION APERTURE</span><h2>選べる接続を、<br/>静かに保つ。</h2><p>再接続だけが成功ではありません。限定接続、延長、退出も同じく正常な選択です。</p></div></div><div className="quick-panel"><h2>いま必要なこと</h2><div className="metric-row"><div><b>{activeContracts.length}</b><span>有効な契約</span></div><div><b>{pending.length}</b><span>確認待ち</span></div><div><b>{activeCooldown ? "1" : "0"}</b><span>Cooldown</span></div></div><div className="quick-actions"><NavLink to="/monku"><MessageSquareText/>Monkuを残す<ChevronRight/></NavLink><NavLink to="/cooldown"><Clock3/>距離を置く<ChevronRight/></NavLink><NavLink className="safety-action" to="/safety"><LifeBuoy/>安全な選択肢<ChevronRight/></NavLink></div></div></section><div className="section-title"><h2>今日の契約</h2><NavLink to="/contracts">すべて見る <ArrowRight/></NavLink></div><section className="card-grid">{activeContracts.length ? activeContracts.slice(0,3).map((c) => <ContractCard key={c.id} contract={c} members={props.data.members}/>) : <Empty icon={<BookOpen/>} title="有効な契約はありません" text="曖昧な期待を、入力・出力・期限のある小さな契約にできます。"/>}</section>{pending.length > 0 && <section className="notice revision-notice"><FileDiff/><div><b>{pending.length}件のRevisionが確認を待っています</b><p>差分と必要な合意を確認してください。</p></div><NavLink className="secondary" to="/revisions">確認する</NavLink></section>}</>;
}

function ContractCard({ contract, members }: { contract: ContractVersion; members: MemberNode[] }) { return <article className="card contract-card"><div className="card-top"><Status tone={contract.status === "active" ? "safe" : "neutral"}>{contract.status}</Status><span>v{contract.version}</span></div><h3>{contract.title}</h3><p className="mono">{contract.input || "入力未設定"} → {contract.output || "出力未設定"}</p><div className="contract-meta"><span><Clock3/> {contract.sla || "期限なし"}</span><span><Users/> {contract.participants.map((id) => members.find((m) => m.id === id)?.displayName).join(" · ")}</span></div></article>; }

function Contracts({ data, member, refresh }: PageProps) {
  const [show, setShow] = useState(false); const [title, setTitle] = useState(""); const [input, setInput] = useState(""); const [output, setOutput] = useState(""); const [sla, setSla] = useState(""); const [kind, setKind] = useState<ContractVersion["kind"]>("shared-resource"); const [participants, setParticipants] = useState(data.members.map((m) => m.id));
  const create = async (e: FormEvent) => { e.preventDefault(); const contractId = uid(); const record: ContractVersion = { id: uid(), contractId, version: 1, kind, title, input, output, sla, participants, boundaries: ["中断を希望したら停止する"], stopConditions: ["再交渉の希望が出たとき"], status: "active", createdBy: member.id, createdAt: nowIso() }; await db.contracts.add(record); await writeAudit(member.id, "contract-created", "contract", contractId); setShow(false); setTitle(""); await refresh(); };
  const visible = data.contracts.filter((c, i, all) => all.findIndex((x) => x.contractId === c.contractId) === i);
  return <><PageHead eyebrow="INTERFACE CONTRACTS" title="契約"><button className="primary" onClick={() => setShow(true)}><Plus/> 新しい契約</button></PageHead><p className="page-intro">内面や善悪ではなく、依頼の入力・出力・期限・停止条件だけを記録します。</p><div className="tabs"><button className="selected">すべて {visible.length}</button><button>Active {visible.filter((c) => c.status === "active").length}</button><button>Draft {visible.filter((c) => c.status === "draft").length}</button><button>Ended {visible.filter((c) => c.status === "ended").length}</button></div><section className="card-grid">{visible.length ? visible.map((c) => <div key={c.id}><ContractCard contract={c} members={data.members}/><button className="text-button revision-link" onClick={async () => { const rev: Revision = { id: uid(), contractId: c.contractId, baseVersion: c.version, proposedVersion: c.version + 1, patch: {}, affectedNodeIds: c.participants, proposer: "member", constitutionCheck: "passed", status: "draft", expiresAt: new Date(Date.now() + 7 * 86400000).toISOString() }; await db.revisions.add(rev); await refresh(); }}>Revisionを作る <FileDiff/></button></div>) : <Empty icon={<BookOpen/>} title="最初の契約を作りましょう" text="例えば「火曜8時までにゴミを出す」を入力と出力に分けます。"/>}</section>{show && <Modal title="新しい契約" onClose={() => setShow(false)}><form onSubmit={create}><label>タイトル<input value={title} onChange={(e) => setTitle(e.target.value)} placeholder="火曜のゴミ出し" required/></label><label>契約種別<select value={kind} onChange={(e) => setKind(e.target.value as ContractVersion["kind"])}><option value="shared-resource">家事・共有資源（過半数）</option><option value="bilateral">個人間（全員）</option><option value="data-sharing">個人データ共有（本人）</option><option value="safety">Safety（本人＋独立確認）</option></select></label><div className="form-grid"><label>入力・依頼<textarea value={input} onChange={(e) => setInput(e.target.value)} required/></label><label>出力・完了条件<textarea value={output} onChange={(e) => setOutput(e.target.value)} required/></label></div><label>期限・SLA<input value={sla} onChange={(e) => setSla(e.target.value)} placeholder="火曜 08:00"/></label><fieldset><legend>影響を受けるメンバー</legend>{data.members.map((m) => <label className="check" key={m.id}><input type="checkbox" checked={participants.includes(m.id)} onChange={() => setParticipants(participants.includes(m.id) ? participants.filter((id) => id !== m.id) : [...participants, m.id])}/>{m.displayName}</label>)}</fieldset><button className="primary wide" disabled={participants.length < 2}>端末内に保存</button></form></Modal>}</>;
}

function Monku({ data, member, sessionKey, refresh }: PageProps) {
  const [body, setBody] = useState(""); const [items, setItems] = useState<Array<{ record: PrivateRecord; value: MonkuValue }>>([]); const load = useCallback(() => privateRepo.listForOwner<MonkuValue>(member.id, "monku", sessionKey).then(setItems), [member.id, sessionKey]); useEffect(() => { load(); }, [load]);
  const save = async (e: FormEvent) => { e.preventDefault(); if (!body.trim()) return; const record = await privateRepo.save(member.id, "monku", { body }, sessionKey); await writeAudit(member.id, "private-note-created", "private-record", record.id); setBody(""); await load(); await refresh(); };
  const convert = async (item: typeof items[number]) => { const contract = data.contracts[0]; if (!contract) return alert("先に契約を1件作成してください"); const suggestion = convertWithLocalTemplate(item.value.body); const check = inspectPatch(suggestion.proposedPatch, "template"); const revision: Revision = { id: uid(), contractId: contract.contractId, baseVersion: contract.version, proposedVersion: contract.version + 1, patch: suggestion.proposedPatch, affectedNodeIds: contract.participants, proposer: "template", constitutionCheck: check.ok ? "passed" : "rejected", status: "draft", expiresAt: new Date(Date.now() + 7 * 86400000).toISOString() }; await db.revisions.add(revision); await db.privateRecords.update(item.record.id, { shareState: "diff-only", convertedRevisionId: revision.id }); await writeAudit(member.id, "revision-draft-created", "revision", revision.id); await load(); await refresh(); };
  return <><PageHead eyebrow="PRIVATE · ENCRYPTED" title="Monku"><Status tone="private"><FileLock2/> {member.displayName}だけ</Status></PageHead><div className="privacy-banner"><LockKeyhole/><div><b>本文はこの端末で暗号化されます</b><p>明示操作なしに他メンバー、AI、外部サービスへ共有されません。</p></div></div><form className="composer" onSubmit={save}><label htmlFor="monku-body">いま残しておきたいこと</label><textarea id="monku-body" value={body} onChange={(e) => setBody(e.target.value)} placeholder="相手を評価せず、まず自分だけの言葉で残せます。" rows={5}/><div className="composer-foot"><span>{body.length}文字 · 外部送信なし</span><button className="primary" disabled={!body.trim()}><FileLock2/> 非公開で保存</button></div></form><div className="section-title"><h2>自分の記録</h2><span>{items.length}件</span></div><section className="stack">{items.length ? items.map((item) => <article className="card monku-card" key={item.record.id}><div className="card-top"><Status tone="private">{item.record.shareState === "private" ? "非公開" : "差分のみ"}</Status><time>{new Date(item.record.createdAt).toLocaleString("ja-JP")}</time></div><p>{item.value.body}</p><div className="card-actions"><button className="secondary" onClick={() => convert(item)} disabled={Boolean(item.record.convertedRevisionId)}><Sparkles/> {item.record.convertedRevisionId ? "差分へ変換済み" : "ローカルテンプレートで差分化"}</button><button className="danger-text" onClick={async () => { await privateRepo.deleteForOwner(item.record.id, member.id); await load(); }}>削除</button></div></article>) : <Empty icon={<MessageSquareText/>} title="まだ記録はありません" text="ここに残した本文は、あなたの操作なしに共有されません。"/>}</section></>;
}

function Revisions({ data, member, refresh }: PageProps) {
  const vote = async (revision: Revision, decision: Consent["decision"]) => { const nextConsent: Consent = { revisionId: revision.id, memberId: member.id, decision, decidedAt: nowIso() }; await db.consents.put(nextConsent); if (decision === "reject") await db.revisions.update(revision.id, { status: "rejected" }); else { const votingRevision = { ...revision, status: "voting" as const }; await db.revisions.update(revision.id, { status: "voting" }); const base = data.contracts.find((c) => c.contractId === revision.contractId && c.version === revision.baseVersion); const allConsents = [...data.consents.filter((c) => c.revisionId === revision.id && c.memberId !== member.id), nextConsent]; if (base) { const result = evaluateConsensus({ kind: base.kind, affectedNodes: data.members.filter((node) => revision.affectedNodeIds.includes(node.id)), consents: allConsents, rightsRestrictedFor: revision.patch.rightsRestrictedFor }); if (result.accepted) { const version = mergeRevision(base, votingRevision, allConsents, data.members); await db.transaction("rw", [db.contracts, db.revisions], async () => { await db.contracts.add(version); await db.revisions.update(revision.id, { status: "accepted" }); }); await writeAudit(member.id, "revision-accepted", "revision", revision.id); } } } await writeAudit(member.id, `consent-${decision}`, "revision", revision.id); await refresh(); };
  return <><PageHead eyebrow="SCHEMA DIFF · CONSENT" title="Revision"/><p className="page-intro">元のMonku本文は表示しません。構造化された変更差分と合意状況だけを確認します。</p><section className="stack">{data.revisions.length ? data.revisions.map((r) => { const contract = data.contracts.find((c) => c.contractId === r.contractId); const affected = data.members.filter((m) => r.affectedNodeIds.includes(m.id)); const consents = data.consents.filter((c) => c.revisionId === r.id); const result = contract ? evaluateConsensus({ kind: contract.kind, affectedNodes: affected, consents, rightsRestrictedFor: r.patch.rightsRestrictedFor }) : undefined; const own = consents.find((c) => c.memberId === member.id); return <article className="revision-card" key={r.id}><div className="revision-head"><div><Status tone={r.constitutionCheck === "passed" ? "safe" : "danger"}><ShieldCheck/> Constitution {r.constitutionCheck}</Status><h2>{contract?.title ?? "契約"} <span>v{r.baseVersion} → v{r.proposedVersion}</span></h2></div><Status>{r.status}</Status></div><div className="diff"><div><span>変更前</span><pre>{JSON.stringify(contract ? { input: contract.input, output: contract.output, sla: contract.sla, boundaries: contract.boundaries } : {}, null, 2)}</pre></div><div className="after"><span>変更案</span><pre>{JSON.stringify(r.patch, null, 2)}</pre></div></div><div className="consensus-line"><Users/><div><b>{result?.approvals ?? 0} / {result?.required ?? affected.length} 承認</b><p>{result?.reason ?? "契約が見つかりません"}</p></div></div>{r.affectedNodeIds.includes(member.id) && !own && r.status !== "rejected" && <div className="vote-actions"><button className="primary" onClick={() => vote(r, "approve")}><Check/> 承認</button><button className="secondary" onClick={() => vote(r, "abstain")}><Clock3/> 保留</button><button className="danger" onClick={() => vote(r, "reject")}><X/> 拒否</button></div>}{own && <p className="decision">あなたの選択: <b>{own.decision}</b></p>}</article>; }) : <Empty icon={<FileDiff/>} title="Revisionはありません" text="契約または非公開Monkuから変更差分を作成できます。"/>}</section></>;
}

function Cooldown({ data, member, refresh }: PageProps) {
  const [duration, setDuration] = useState(30); const [targets, setTargets] = useState<string[]>([]); const [channels, setChannels] = useState<CooldownSession["allowedChannels"]>(["sos", "logistics"]); const active = data.cooldowns.filter((c) => c.initiatedBy === member.id && cooldownState(c) !== "closed");
  const start = async (e: FormEvent) => { e.preventDefault(); const session = createCooldown({ initiatedBy: member.id, targetConnectionIds: targets, allowedChannels: channels.includes("sos") ? channels : ["sos", ...channels], durationMinutes: duration }); await db.cooldowns.add(session); await writeAudit(member.id, "cooldown-started", "cooldown", session.id); await refresh(); };
  const close = async (session: CooldownSession, outcome: NonNullable<CooldownSession["outcome"]>) => { await db.cooldowns.put(closeCooldown(session, outcome)); await writeAudit(member.id, `cooldown-${outcome}`, "cooldown", session.id); await refresh(); };
  return <><PageHead eyebrow="COOLING · MANUAL" title="距離を置く"><Status tone="safe">SOSは常に利用可能</Status></PageHead><p className="page-intro">誰が正しいかを判定せず、連絡方法を一時的に絞ります。物理アクセスや通信は遮断しません。</p>{active.map((session) => <article className="cooldown-active" key={session.id}><div className="timer-icon"><Clock3/></div><div><div className="eyebrow">{cooldownState(session) === "active" ? "COOLDOWN ACTIVE" : "NEXT STEP REQUIRED"}</div><h2>{cooldownState(session) === "active" ? new Date(session.expiresAt).toLocaleTimeString("ja-JP", { hour: "2-digit", minute: "2-digit" }) + " まで" : "次の接続状態を選んでください"}</h2><p>許可チャネル: {session.allowedChannels.join(" · ")}</p></div><div className="outcome-actions"><button onClick={() => close(session, "limited")}>限定接続</button><button onClick={() => close(session, "extend")}>延長を検討</button><button onClick={() => close(session, "exit")}>退出</button><button onClick={() => close(session, "reconnect")}>通常接続</button></div></article>)}<form className="card form-card" onSubmit={start}><h2>新しいCooldown</h2><fieldset><legend>対象の接続</legend>{data.members.filter((m) => m.id !== member.id).map((m) => <label className="check" key={m.id}><input type="checkbox" checked={targets.includes(m.id)} onChange={() => setTargets(targets.includes(m.id) ? targets.filter((id) => id !== m.id) : [...targets, m.id])}/>{m.displayName}</label>)}</fieldset><label>期間<select value={duration} onChange={(e) => setDuration(Number(e.target.value))}><option value={15}>15分</option><option value={30}>30分</option><option value={60}>1時間</option><option value={180}>3時間</option></select></label><fieldset><legend>許可する連絡方法</legend><label className="check"><input type="checkbox" checked disabled/>SOS（無効化不可）</label>{(["logistics", "text"] as const).map((c) => <label className="check" key={c}><input type="checkbox" checked={channels.includes(c)} onChange={() => setChannels(channels.includes(c) ? channels.filter((x) => x !== c) : [...channels, c])}/>{c === "logistics" ? "生活上の連絡" : "テキスト"}</label>)}</fieldset><button className="primary" disabled={!targets.length}><Clock3/> 距離を置く</button></form></>;
}

function Safety({ data, member, sessionKey, refresh }: PageProps) {
  const [stage, setStage] = useState<"start" | "private">("start"); const [note, setNote] = useState(""); const [contacts, setContacts] = useState<Array<{ record: PrivateRecord; value: SafeContact }>>([]); const activeLeases = data.leases.filter((l) => leaseState(l) === "active"); useEffect(() => { privateRepo.listForOwner<SafeContact>(member.id, "safe-channel", sessionKey).then(setContacts); return () => { setNote(""); }; }, [member.id, sessionKey]);
  const record = async (action: SafetyValue["action"]) => { const incidentId = uid(); const saved = await privateRepo.save<SafetyValue>(member.id, "safety", { note, action }, sessionKey); await writeAudit(member.id, "protected-interrupt-created", "safety-incident", incidentId); setNote(""); if (action === "local") alert("端末内に暗号化して保存しました。外部送信はありません。"); else alert("MVPでは外部送信しません。表示された連絡先を本人が別の手段で利用してください。"); return saved; };
  const lease = async () => { const incidentId = uid(); const issuedAt = new Date(); const candidate = issueLease({ incidentId, grantee: "本人が指定した確認先", scope: ["safety-check"], purpose: `incident:${incidentId} の安全確認`, issuedAt: issuedAt.toISOString(), expiresAt: new Date(issuedAt.getTime() + 30 * 60_000).toISOString() }); if (!inspectLease(candidate).ok) return; await db.leases.add(candidate); await writeAudit(member.id, "capability-issued", "capability-lease", candidate.id); await refresh(); };
  return <div className="safety-page"><PageHead eyebrow="PROTECTED INTERRUPT" title="安全な選択肢"/><div className="safety-warning"><AlertTriangle/><p><b>今すぐ危険がある場合</b><br/>このアプリの操作より、現実の安全確保と地域の緊急連絡先を優先してください。</p></div>{stage === "start" ? <section className="safety-start"><div className="safety-orb"><LifeBuoy/></div><h2>SOSは判決ではありません。</h2><p>あなたの安全を確認するための、保護された割り込みです。誰かへ自動通知されず、送信者も自動開示されません。</p><button className="primary wide" onClick={() => setStage("private")}>本人専用画面を開く <ArrowRight/></button></section> : <section className="safety-private"><Status tone="private"><FileLock2/> 本人専用</Status><h2>いま選べること</h2><label>端末内だけに残すメモ（任意）<textarea value={note} onChange={(e) => setNote(e.target.value)} rows={4}/></label><div className="safety-options"><button onClick={() => record("local")}><FileLock2/><div><b>端末内に記録</b><span>暗号化して保存。送信なし</span></div><ChevronRight/></button><button onClick={() => record("contact")}><Users/><div><b>Safe Channelを確認</b><span>{contacts.length ? contacts.map((c) => `${c.value.name}: ${c.value.contact}`).join(" / ") : "設定に連絡先はありません"}</span></div><ChevronRight/></button><button onClick={() => record("emergency")}><LifeBuoy/><div><b>現実の緊急連絡先を使う</b><span>アプリは発信・送信しません</span></div><ChevronRight/></button></div><button className="secondary" onClick={lease}>30分の安全確認Leaseをローカル発行</button></section>}<div className="section-title"><h2>有効なCapability Lease</h2><span>{activeLeases.length}件</span></div>{activeLeases.map((l) => <article className="lease" key={l.id}><ShieldCheck/><div><b>{l.scope.join(" · ")}</b><p>{l.purpose}</p><span>{new Date(l.expiresAt).toLocaleString("ja-JP")} に自動失効</span></div><button className="danger-text" onClick={async () => { await db.leases.update(l.id, { revokedAt: nowIso() }); await refresh(); }}>取消</button></article>)}</div>;
}

function SettingsPage({ data, member, refresh, onReset }: PageProps & { onReset: () => void }) {
  const [passphrase, setPassphrase] = useState(""); const [auditOk, setAuditOk] = useState<boolean>(); const flags = [{ label: "AI", key: "ai", desc: "リモートAI adapter" }, { label: "クラウド同期", key: "cloud", desc: "端末外への同期" }, { label: "外部送信", key: "send", desc: "SOS・連絡先への送信" }];
  const download = async () => { const blob = await exportEncrypted(passphrase); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `aperture-home-${new Date().toISOString().slice(0,10)}.encrypted.json`; anchor.click(); URL.revokeObjectURL(url); setPassphrase(""); };
  return <><PageHead eyebrow="DEVICE · PRIVACY" title="設定"/><section className="settings-grid"><article className="settings-card"><h2><Users/> メンバーと端末</h2>{data.members.map((m) => <div className="setting-row" key={m.id}><span>{m.displayName}</span><Status>{m.id === member.id ? "この端末利用者" : "ロック中"}</Status></div>)}</article><article className="settings-card"><h2><WifiOff/> 外部機能</h2>{flags.map((f) => <div className="setting-row" key={f.key}><div><b>{f.label}</b><span>{f.desc}</span></div><Status tone="safe">無効</Status></div>)}<p className="field-help">この実験版には有効化操作がありません。</p></article><article className="settings-card span-2"><h2><ShieldCheck/> Protocol Constitution v1.0</h2><ol className="constitution-list">{PROTOCOL_CONSTITUTION.map((clause) => <li key={clause}>{clause}</li>)}</ol></article><article className="settings-card"><h2><FileLock2/> 暗号化バックアップ</h2><label>10文字以上のパスフレーズ<input type="password" value={passphrase} minLength={10} onChange={(e) => setPassphrase(e.target.value)}/></label><button className="secondary wide" disabled={passphrase.length < 10} onClick={download}>暗号化してエクスポート</button><label className="file-input">暗号化バックアップをインポート<input type="file" accept="application/json" onChange={async (e) => { const file = e.target.files?.[0]; if (file && passphrase.length >= 10) { await importEncrypted(await file.text(), passphrase); await refresh(); } }}/></label></article><article className="settings-card"><h2><ShieldCheck/> 監査ログ</h2><p>秘密本文を含まない{data.audit.length}件の追記ログがあります。</p><button className="secondary wide" onClick={async () => setAuditOk(await verifyAuditChain(data.audit))}>整合性を確認</button>{auditOk !== undefined && <Status tone={auditOk ? "safe" : "danger"}>{auditOk ? "ハッシュチェーンは整合" : "改ざんの可能性"}</Status>}</article><article className="settings-card danger-zone span-2"><h2>全データを完全削除</h2><p>このブラウザの契約、非公開記録、暗号化データ、監査ログを削除します。復元できません。</p><button className="danger" onClick={async () => { if (confirm("この端末のAperture Homeデータを完全に削除します。復元できません。続けますか？")) { await deleteAllData(); localStorage.clear(); onReset(); location.reload(); } }}>全データを削除</button></article></section></>;
}

function Modal({ title, onClose, children }: { title: string; onClose: () => void; children: React.ReactNode }) { return <div className="modal-backdrop" role="presentation" onMouseDown={(e) => { if (e.currentTarget === e.target) onClose(); }}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title"><header><h2 id="modal-title">{title}</h2><button className="icon-button" onClick={onClose} aria-label="閉じる"><X/></button></header>{children}</section></div>; }
